export const menus = [
  { id: 1, restoId: "AQvcvZZlXtUImIopXhsC", name: "Big Mac", price: 5.99 },
  { id: 2, restoId: "AQvcvZZlXtUImIopXhsC", name: "McChicken", price: 4.49 },
  { id: 3, restoId: "AQvcvZZlXtUImIopXhsC", name: "Fries", price: 2.99 },
  { id: 4, restoId: "AQvcvZZlXtUImIopXhsC", name: "Coca Cola", price: 1.99 },
  { id: 5, restoId: "AQvcvZZlXtUImIopXhsC", name: "Nuggets", price: 3.99 },
  { id: 6, restoId: "AQvcvZZlXtUImIopXhsC", name: "Frite", price: 3.99 },
  { id: 7, restoId: "B6jiWaL7IgaCsiAoXpMK", name: "Algérienne", price: 3.99 },
  { id: 8, restoId: "B6jiWaL7IgaCsiAoXpMK", name: "Barbecue", price: 3.99 },
  { id: 9, restoId: "B6jiWaL7IgaCsiAoXpMK", name: "Biggy Burger", price: 3.99 },
  {
    id: 10,
    restoId: "B6jiWaL7IgaCsiAoXpMK",
    name: "Eau Aquafina",
    price: 3.99,
  },
  {
    id: 11,
    restoId: "B6jiWaL7IgaCsiAoXpMK",
    name: "Mirinda Citron",
    price: 3.99,
  },
  {
    id: 12,
    restoId: "B6jiWaL7IgaCsiAoXpMK",
    name: "Mirinda Pomme",
    price: 3.99,
  },
  {
    id: 13,
    restoId: "Ha2bKyksCxzpKMteCsz6",
    name: "Super - Deals",
    price: 3.99,
  },
  { id: 14, restoId: "Ha2bKyksCxzpKMteCsz6", name: "Nos Salades", price: 3.99 },
  { id: 15, restoId: "Ha2bKyksCxzpKMteCsz6", name: "Nos Tacos", price: 3.99 },
  { id: 16, restoId: "Ha2bKyksCxzpKMteCsz6", name: "Nos Pizzas", price: 3.99 },
  { id: 17, restoId: "Ha2bKyksCxzpKMteCsz6", name: "Nos Burgers", price: 3.99 },
  {
    id: 18,
    restoId: "Ha2bKyksCxzpKMteCsz6",
    name: "Nos Sandwichs",
    price: 3.99,
  },
  { id: 19, restoId: "NmCjA4acb3UkZbzPa4kh", name: "Nouveautés", price: 3.99 },
  { id: 20, restoId: "NmCjA4acb3UkZbzPa4kh", name: "Promos", price: 3.99 },
  { id: 21, restoId: "NmCjA4acb3UkZbzPa4kh", name: "Burgers", price: 3.99 },
  {
    id: 22,
    restoId: "NmCjA4acb3UkZbzPa4kh",
    name: "Menus Enfants",
    price: 3.99,
  },
  { id: 23, restoId: "NmCjA4acb3UkZbzPa4kh", name: "Desserts", price: 3.99 },
  { id: 24, restoId: "NmCjA4acb3UkZbzPa4kh", name: "Boissons", price: 3.99 },
  {
    id: 25,
    restoId: "TkOQR0LZJqVo6pA9Pl4N",
    name: "Glaces & Desserts",
    price: 3.99,
  },
  { id: 26, restoId: "TkOQR0LZJqVo6pA9Pl4N", name: "Boissons", price: 3.99 },
  {
    id: 27,
    restoId: "TkOQR0LZJqVo6pA9Pl4N",
    name: "Pizzas - Pâte Thin",
    price: 3.99,
  },
  {
    id: 28,
    restoId: "TkOQR0LZJqVo6pA9Pl4N",
    name: "Pizzas - Pâte Pan",
    price: 3.99,
  },
  {
    id: 29,
    restoId: "TkOQR0LZJqVo6pA9Pl4N",
    name: "Pizzas - Pâte Cheezy Crust",
    price: 3.99,
  },
  {
    id: 30,
    restoId: "TkOQR0LZJqVo6pA9Pl4N",
    name: "Sandwichs & Calzones",
    price: 3.99,
  },
  { id: 31, restoId: "ZWNYv4rcouIqqwKBkazM", name: "Buckets", price: 3.99 },
  {
    id: 32,
    restoId: "ZWNYv4rcouIqqwKBkazM",
    name: "Exclusive Promotions",
    price: 3.99,
  },
  { id: 33, restoId: "ZWNYv4rcouIqqwKBkazM", name: "Boxes", price: 3.99 },
  { id: 34, restoId: "ZWNYv4rcouIqqwKBkazM", name: "Menus", price: 3.99 },
  { id: 35, restoId: "ZWNYv4rcouIqqwKBkazM", name: "Sandwich", price: 3.99 },
  {
    id: 36,
    restoId: "ZWNYv4rcouIqqwKBkazM",
    name: "Sides & Drinks",
    price: 3.99,
  },
  { id: 37, restoId: "m2oJn7lE0lMr46kA41gS", name: "Boucherie", price: 3.99 },
  { id: 38, restoId: "m2oJn7lE0lMr46kA41gS", name: "Volaille", price: 3.99 },
  {
    id: 39,
    restoId: "m2oJn7lE0lMr46kA41gS",
    name: "Poissonnerie",
    price: 3.99,
  },
  {
    id: 40,
    restoId: "m2oJn7lE0lMr46kA41gS",
    name: "Traiteur de la Mer",
    price: 3.99,
  },
  { id: 41, restoId: "m2oJn7lE0lMr46kA41gS", name: "Fruits", price: 3.99 },
  {
    id: 42,
    restoId: "m2oJn7lE0lMr46kA41gS",
    name: "Prêt à manger",
    price: 3.99,
  },
];
